/** llvm-version.hpp
 * Copyright © 2021 Gene Harvey
 *
 * This software may be modified and distributed under the terms
 * of the MIT license. See the LICENSE file for details.
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */

#ifndef OCTAVE_IR_COMPILER_LLVM_LLVM_VERSION_HPP
#define OCTAVE_IR_COMPILER_LLVM_LLVM_VERSION_HPP

#include <llvm/Config/llvm-config.h>

#ifndef LLVM_VERSION_PATCH
#  define LLVM_VERSION_PATCH 0
#endif

#define GCH_LLVM_VERSION_MAJOR_NUM(MAJOR) ((MAJOR) * 010000L)
#define GCH_LLVM_VERSION_MINOR_NUM(MINOR) ((MINOR) * 000100L)
#define GCH_LLVM_VERSION_PATCH_NUM(PATCH) ((PATCH) * 000001L)

#define GCH_LLVM_VERSION_NUM(MAJOR, MINOR, PATCH) \
  GCH_LLVM_VERSION_MAJOR_NUM (MAJOR)              \
+ GCH_LLVM_VERSION_MINOR_NUM (MINOR)              \
+ GCH_LLVM_VERSION_PATCH_NUM (PATCH)

#ifndef GCH_LLVM_VERSION
#  define GCH_LLVM_VERSION GCH_LLVM_VERSION_NUM (LLVM_VERSION_MAJOR, \
                                                 LLVM_VERSION_MINOR, \
                                                 LLVM_VERSION_PATCH)
#endif

#define GCH_LLVM_VERSION_EQUAL(MAJOR, MINOR, PATCH) \
(GCH_LLVM_VERSION == GCH_LLVM_VERSION_NUM (MAJOR, MINOR, PATCH))

#define GCH_LLVM_VERSION_LESS(MAJOR, MINOR, PATCH) \
(GCH_LLVM_VERSION < GCH_LLVM_VERSION_NUM (MAJOR, MINOR, PATCH))

#define GCH_LLVM_VERSION_GREATER_EQUAL(MAJOR, MINOR, PATCH) \
(! GCH_LLVM_VERSION_LESS (MAJOR, MINOR, PATCH))

#define GCH_LLVM_VERSION_GREATER(MAJOR, MINOR, PATCH) \
(GCH_LLVM_VERSION_NUM (MAJOR, MINOR, PATCH) < GCH_LLVM_VERSION)

#define GCH_LLVM_VERSION_LESS_EQUAL(MAJOR, MINOR, PATCH) \
(! GCH_LLVM_VERSION_GREATER (MAJOR, MINOR, PATCH))

#define GCH_LLVM_VERSION_MAJOR_EQUAL(MAJOR) \
GCH_LLVM_VERSION_EQUAL (MAJOR, 00, 00)

#define GCH_LLVM_VERSION_MAJOR_LESS(MAJOR) \
GCH_LLVM_VERSION_LESS (MAJOR, 00, 00)

#define GCH_LLVM_VERSION_MAJOR_GREATER_EQUAL(MAJOR) \
GCH_LLVM_VERSION_GREATER_EQUAL (MAJOR, 00, 00)

#define GCH_LLVM_VERSION_MAJOR_GREATER(MAJOR) \
GCH_LLVM_VERSION_GREATER (MAJOR, 00, 00) < GCH_LLVM_VERSION

#define GCH_LLVM_VERSION_MAJOR_LESS_EQUAL(MAJOR) \
GCH_LLVM_VERSION_LESS_EQUAL (MAJOR, 00, 00)

#define GCH_LLVM_HAS_ORC           GCH_LLVM_VERSION_GREATER_EQUAL (3, 7, 0)
#define GCH_LLVM_HAS_ORCV2         GCH_LLVM_VERSION_MAJOR_GREATER_EQUAL (7)
#define GCH_LLVM_HAS_DEFAULT_ORCV2 GCH_LLVM_VERSION_MAJOR_GREATER_EQUAL (8)

#endif // OCTAVE_IR_COMPILER_LLVM_LLVM_VERSION_HPP
